### ISSUE TITLE
README uses deprecated action nrwl/last-successful-commit-action

### ISSUE THREAD

**Issue by JasonWeinzierl** [leonardochaia/dotnet-affected-action#239]
The example in the README uses `nrwl/last-successful-commit-action` which is deprecated in favor of `nrwl/nx-set-shas`.  Could it be updated?

Should it be something like this?

```yml
      - uses: nrwl/nx-set-shas@v4
        id: set_shas

      - uses: leonardochaia/dotnet-affected-action@v1
        id: dotnet_affected
        with:
          from: ${{ steps.set_shas.outputs.base }}
          to: ${{ steps.set_shas.outputs.head }}
```
